/**
 * Canvas drawing.
 *
 * VISUAL HONESTY RULES, which are part of the lab's correctness and not a style
 * preference:
 *
 *  - The private (short, nearly orthogonal) basis is always warm/accent; the
 *    public (long, skewed) basis is always neutral. Never swapped.
 *  - Both bases are drawn at ONE shared scale. Rescaling them independently
 *    would hide the orthogonality defect, which is the single thing Act 1
 *    exists to show.
 *  - The lattice points are REAL points of L(R) = L(B), sampled and projected.
 *    The alt text used to promise lattice points while the renderer drew only
 *    axes and arrows; an external audit caught that. They are drawn now, and the
 *    caption says plainly that it is a sample and a projection.
 *  - The parallelepiped in Act 4 is the ACTUAL projection of P(R), computed as
 *    the zonogon generated by the projected basis rows. It is never a drawn
 *    rectangle. The corners are the whole point of the Nguyen-Regev attack, so a
 *    stylised box would contradict the lesson.
 *  - The error vector is never drawn longer than it is relative to the basis, so
 *    the picture agrees with invariant I2.
 *
 * RESOLUTION. The canvas backing store is sized from its real CSS box times
 * devicePixelRatio, so a 720x360 bitmap is no longer squashed into 241x120 on a
 * 320 px screen. Legends and captions are HTML, not painted pixels, so they stay
 * readable and selectable at any width and are available to a screen reader.
 */

import type { Mat, Vec, Rng } from '../lattice/types';
import { vecMat } from '../lattice/matrix';

/** Two coordinates chosen for the projection plane. */
export interface Projection {
  readonly i: number;
  readonly j: number;
}

interface Viewport {
  cx: number;
  cy: number;
  scale: number;
  w: number;
  h: number;
}

export interface LegendEntry {
  readonly color: string;
  readonly text: string;
}

function styles(): Record<string, string> {
  const cs = getComputedStyle(document.documentElement);
  const get = (n: string, fallback: string) => cs.getPropertyValue(n).trim() || fallback;
  return {
    priv: get('--basis-private', '#35d6bb'),
    pub: get('--basis-public', '#9aa9bd'),
    grid: get('--border', '#33404f'),
    text: get('--text-muted', '#93a2b6'),
    surface: get('--surface-2', '#18202d'),
    bad: get('--bad', '#ff8095'),
    point: get('--text-muted', '#93a2b6'),
  };
}

/**
 * Size the backing store to the element's real CSS box times devicePixelRatio,
 * and return a context already scaled so all drawing can use CSS pixels.
 */
function prepare(canvas: HTMLCanvasElement): { ctx: CanvasRenderingContext2D; w: number; h: number } | null {
  const ctx = canvas.getContext('2d');
  if (!ctx) return null;
  const rect = canvas.getBoundingClientRect();
  // Before first layout the rect can be zero; fall back to the attribute size.
  const cssW = Math.max(1, Math.round(rect.width || canvas.width));
  const cssH = Math.max(1, Math.round(rect.height || canvas.height));
  const dpr = Math.min(window.devicePixelRatio || 1, 3);
  const backingW = Math.round(cssW * dpr);
  const backingH = Math.round(cssH * dpr);
  if (canvas.width !== backingW || canvas.height !== backingH) {
    canvas.width = backingW;
    canvas.height = backingH;
  }
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  return { ctx, w: cssW, h: cssH };
}

function fitViewport(w: number, h: number, points: Array<[number, number]>, pad = 14): Viewport {
  let max = 1e-9;
  for (const [x, y] of points) max = Math.max(max, Math.abs(x), Math.abs(y));
  const half = Math.min(w, h) / 2 - pad;
  return { cx: w / 2, cy: h / 2, scale: Math.max(half, 1) / max, w, h };
}

function toScreen(v: Viewport, x: number, y: number): [number, number] {
  return [v.cx + x * v.scale, v.cy - y * v.scale];
}

function clear(ctx: CanvasRenderingContext2D, v: Viewport, s: Record<string, string>) {
  ctx.clearRect(0, 0, v.w, v.h);
  ctx.fillStyle = s.surface;
  ctx.fillRect(0, 0, v.w, v.h);
}

function drawAxes(ctx: CanvasRenderingContext2D, v: Viewport, s: Record<string, string>) {
  ctx.strokeStyle = s.grid;
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(0, v.cy);
  ctx.lineTo(v.w, v.cy);
  ctx.moveTo(v.cx, 0);
  ctx.lineTo(v.cx, v.h);
  ctx.stroke();
}

function arrow(
  ctx: CanvasRenderingContext2D,
  v: Viewport,
  x: number,
  y: number,
  color: string,
  width: number,
) {
  const [sx, sy] = toScreen(v, 0, 0);
  const [ex, ey] = toScreen(v, x, y);
  ctx.strokeStyle = color;
  ctx.fillStyle = color;
  ctx.lineWidth = width;
  ctx.beginPath();
  ctx.moveTo(sx, sy);
  ctx.lineTo(ex, ey);
  ctx.stroke();
  const ang = Math.atan2(ey - sy, ex - sx);
  const h = 6;
  ctx.beginPath();
  ctx.moveTo(ex, ey);
  ctx.lineTo(ex - h * Math.cos(ang - 0.4), ey - h * Math.sin(ang - 0.4));
  ctx.lineTo(ex - h * Math.cos(ang + 0.4), ey - h * Math.sin(ang + 0.4));
  ctx.closePath();
  ctx.fill();
}

/** Render a legend as HTML so its type stays readable and a reader can hear it. */
export function renderLegend(host: HTMLElement, entries: LegendEntry[]): void {
  host.innerHTML = '';
  const ul = document.createElement('ul');
  ul.className = 'plot-legend';
  for (const e of entries) {
    const li = document.createElement('li');
    const swatch = document.createElement('span');
    swatch.className = 'plot-swatch';
    swatch.style.background = e.color;
    swatch.setAttribute('aria-hidden', 'true');
    li.appendChild(swatch);
    li.appendChild(document.createTextNode(e.text));
    ul.appendChild(li);
  }
  host.appendChild(ul);
}

/**
 * A sample of genuine lattice points, projected.
 *
 * Each point is x*R for a sparse integer x, so every one is really in L(R) --
 * and because L(R) = L(B) (proved on this page, exactly), the identical point
 * set is generated by the public basis. That is the claim Act 1 makes, so the
 * picture is built from real points rather than a decorative grid.
 */
export function sampleLatticePoints(R: Mat, rng: Rng, count = 260, support = 3): Vec[] {
  const n = R.length;
  const out: Vec[] = [];
  for (let t = 0; t < count; t++) {
    const x = new Float64Array(n);
    const k = 1 + Math.floor(rng() * support);
    for (let q = 0; q < k; q++) {
      const idx = Math.floor(rng() * n);
      x[idx] += rng() < 0.5 ? 1 : -1;
    }
    out.push(vecMat(x, R));
  }
  return out;
}

/**
 * Act 1: real lattice points, with both bases drawn over them at one shared scale.
 *
 * The warm starburst is tight and near-orthogonal; the neutral one sprawls. That
 * difference IS the orthogonality defect the panel reports numerically, and
 * drawing them at different scales would erase it.
 */
export function drawBases(
  canvas: HTMLCanvasElement,
  R: Mat,
  B: Mat,
  proj: Projection,
  points: Vec[],
): LegendEntry[] {
  const prep = prepare(canvas);
  if (!prep) return [];
  const { ctx, w, h } = prep;
  const s = styles();

  const pts: Array<[number, number]> = [];
  for (const row of R) pts.push([row[proj.i], row[proj.j]]);
  for (const row of B) pts.push([row[proj.i], row[proj.j]]);
  const projected: Array<[number, number]> = points.map((p) => [p[proj.i], p[proj.j]]);
  // Fit to the basis vectors, not to the point cloud: a few far-flung sample
  // points must not shrink the vectors this panel exists to compare.
  const v = fitViewport(w, h, pts);
  clear(ctx, v, s);
  drawAxes(ctx, v, s);

  ctx.fillStyle = s.point;
  ctx.globalAlpha = 0.5;
  for (const [x, y] of projected) {
    const [sx, sy] = toScreen(v, x, y);
    if (sx < -4 || sy < -4 || sx > w + 4 || sy > h + 4) continue;
    ctx.beginPath();
    ctx.arc(sx, sy, 1.6, 0, Math.PI * 2);
    ctx.fill();
  }
  ctx.globalAlpha = 1;

  // Public basis first, so the short private vectors are never hidden under it.
  for (const row of B) arrow(ctx, v, row[proj.i], row[proj.j], s.pub, 1.2);
  for (const row of R) arrow(ctx, v, row[proj.i], row[proj.j], s.priv, 2.2);

  return [
    { color: s.point, text: `${points.length} real lattice points, sampled as integer combinations and projected onto coordinates ${proj.i} and ${proj.j}` },
    { color: s.priv, text: 'private basis R (short, nearly orthogonal)' },
    { color: s.pub, text: 'public basis B (long, skewed) - same lattice, same scale' },
  ];
}

/**
 * The exact projection of the fundamental parallelepiped
 * P(R) = { x*R : x in [-1/2, 1/2)^n }.
 *
 * Projecting a parallelepiped gives a ZONOGON -- the Minkowski sum of the
 * projected basis rows as segments -- not a parallelogram. Computed by sorting
 * the generators by angle and walking them, which traces the convex hull
 * exactly. This is why the shape has many corners rather than four, and those
 * corners are exactly what leaks the basis.
 */
export function zonogon(rows: Array<[number, number]>): Array<[number, number]> {
  const gens = rows
    .map(([x, y]) => {
      // The zonotope is symmetric, so fold every generator into the upper half
      // plane before sorting by angle.
      const ang = Math.atan2(y, x);
      return ang < 0 || (ang === 0 && x < 0) ? ([-x, -y] as [number, number]) : ([x, y] as [number, number]);
    })
    .filter(([x, y]) => Math.abs(x) > 1e-12 || Math.abs(y) > 1e-12);
  gens.sort((a, b) => Math.atan2(a[1], a[0]) - Math.atan2(b[1], b[0]));
  let px = 0;
  let py = 0;
  for (const [x, y] of gens) {
    px -= x / 2;
    py -= y / 2;
  }
  const out: Array<[number, number]> = [[px, py]];
  for (const [x, y] of gens) {
    px += x;
    py += y;
    out.push([px, py]);
  }
  for (const [x, y] of gens) {
    px -= x;
    py -= y;
    out.push([px, py]);
  }
  return out;
}

/**
 * Act 4: the signature cloud.
 *
 * Each dot is one signature offset s - h. Under round-off signing these fill
 * P(R) uniformly, right into the corners; under Gaussian (Klein) signing they
 * form a round blob that has no corners to learn.
 */
export function drawSignatureCloud(
  canvas: HTMLCanvasElement,
  offsets: Vec[],
  R: Mat | null,
  proj: Projection,
  opts: { showParallelepiped: boolean; recovered?: Mat | null } = { showParallelepiped: true },
): LegendEntry[] {
  const prep = prepare(canvas);
  if (!prep) return [];
  const { ctx, w, h } = prep;
  const s = styles();

  const pts: Array<[number, number]> = offsets.map((o) => [o[proj.i], o[proj.j]]);
  let hull: Array<[number, number]> = [];
  if (R && opts.showParallelepiped) {
    hull = zonogon(R.map((row) => [row[proj.i], row[proj.j]] as [number, number]));
  }
  const v = fitViewport(w, h, pts.concat(hull));
  clear(ctx, v, s);
  drawAxes(ctx, v, s);

  ctx.fillStyle = s.pub;
  ctx.globalAlpha = 0.55;
  for (const [x, y] of pts) {
    const [sx, sy] = toScreen(v, x, y);
    ctx.fillRect(sx - 1, sy - 1, 2, 2);
  }
  ctx.globalAlpha = 1;

  if (hull.length > 2) {
    ctx.strokeStyle = s.priv;
    ctx.lineWidth = 1.8;
    ctx.beginPath();
    const [x0, y0] = toScreen(v, hull[0][0], hull[0][1]);
    ctx.moveTo(x0, y0);
    for (let i = 1; i < hull.length; i++) {
      const [sx, sy] = toScreen(v, hull[i][0], hull[i][1]);
      ctx.lineTo(sx, sy);
    }
    ctx.closePath();
    ctx.stroke();
  }

  if (opts.recovered) {
    ctx.strokeStyle = s.bad;
    ctx.setLineDash([4, 3]);
    ctx.lineWidth = 1.6;
    for (const row of opts.recovered) {
      const [sx, sy] = toScreen(v, 0, 0);
      const [ex, ey] = toScreen(v, row[proj.i] / 2, row[proj.j] / 2);
      ctx.beginPath();
      ctx.moveTo(sx, sy);
      ctx.lineTo(ex, ey);
      ctx.stroke();
    }
    ctx.setLineDash([]);
  }

  const items: LegendEntry[] = [
    { color: s.pub, text: `${offsets.length} signature offsets s - h, projected onto coordinates ${proj.i} and ${proj.j}` },
  ];
  if (hull.length > 2) {
    items.push({ color: s.priv, text: 'the true fundamental parallelepiped P(R), projected exactly as a zonogon' });
  }
  if (opts.recovered) items.push({ color: s.bad, text: 'basis directions the attack recovered' });
  return items;
}

/** Draw nothing but a message -- used before an exhibit has been run. */
export function drawPlaceholder(canvas: HTMLCanvasElement, message: string): void {
  const prep = prepare(canvas);
  if (!prep) return;
  const { ctx, w, h } = prep;
  const s = styles();
  const v = { cx: w / 2, cy: h / 2, scale: 1, w, h };
  clear(ctx, v, s);
  ctx.fillStyle = s.text;
  ctx.font = '13px ui-monospace, Menlo, Consolas, monospace';
  ctx.textAlign = 'center';
  ctx.fillText(message, w / 2, h / 2);
  ctx.textAlign = 'start';
}
