/**
 * Canvas drawing.
 *
 * VISUAL HONESTY RULES, which are part of the lab's correctness and not a style
 * preference:
 *
 *  - The private (short, nearly orthogonal) basis is always warm/accent; the
 *    public (long, skewed) basis is always neutral. Never swapped.
 *  - Both bases are drawn at ONE shared scale. Rescaling them independently
 *    would hide the orthogonality defect, which is the single thing Act 1
 *    exists to show.
 *  - The parallelepiped in Act 4 is the ACTUAL projection of P(R), computed as
 *    the zonogon generated by the projected basis rows. It is never a drawn
 *    rectangle. The corners are the whole point of the Nguyen-Regev attack, so
 *    a stylised box would contradict the lesson.
 *  - The error vector is never drawn longer than it is relative to the basis,
 *    so the picture agrees with invariant I2.
 */

import type { Mat, Vec } from '../lattice/types';

/** Two coordinates chosen for the projection plane. */
export interface Projection {
  readonly i: number;
  readonly j: number;
}

interface Viewport {
  cx: number;
  cy: number;
  scale: number;
}

function styles(): Record<string, string> {
  const cs = getComputedStyle(document.documentElement);
  const get = (n: string, fallback: string) => cs.getPropertyValue(n).trim() || fallback;
  return {
    priv: get('--basis-private', '#35d6bb'),
    pub: get('--basis-public', '#9aa9bd'),
    grid: get('--border', '#33404f'),
    text: get('--text-muted', '#93a2b6'),
    surface: get('--surface-2', '#18202d'),
    bad: get('--bad', '#ff8095'),
  };
}

function fitViewport(
  canvas: HTMLCanvasElement,
  points: Array<[number, number]>,
  pad = 26,
): Viewport {
  let max = 1e-9;
  for (const [x, y] of points) {
    max = Math.max(max, Math.abs(x), Math.abs(y));
  }
  const half = Math.min(canvas.width, canvas.height) / 2 - pad;
  return { cx: canvas.width / 2, cy: canvas.height / 2, scale: half / max };
}

function toScreen(v: Viewport, x: number, y: number): [number, number] {
  return [v.cx + x * v.scale, v.cy - y * v.scale];
}

function clear(ctx: CanvasRenderingContext2D, canvas: HTMLCanvasElement, s: Record<string, string>) {
  ctx.clearRect(0, 0, canvas.width, canvas.height);
  ctx.fillStyle = s.surface;
  ctx.fillRect(0, 0, canvas.width, canvas.height);
}

function drawAxes(
  ctx: CanvasRenderingContext2D,
  canvas: HTMLCanvasElement,
  v: Viewport,
  s: Record<string, string>,
) {
  ctx.strokeStyle = s.grid;
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.moveTo(0, v.cy);
  ctx.lineTo(canvas.width, v.cy);
  ctx.moveTo(v.cx, 0);
  ctx.lineTo(v.cx, canvas.height);
  ctx.stroke();
}

function arrow(
  ctx: CanvasRenderingContext2D,
  v: Viewport,
  x: number,
  y: number,
  color: string,
  width: number,
) {
  const [sx, sy] = toScreen(v, 0, 0);
  const [ex, ey] = toScreen(v, x, y);
  ctx.strokeStyle = color;
  ctx.fillStyle = color;
  ctx.lineWidth = width;
  ctx.beginPath();
  ctx.moveTo(sx, sy);
  ctx.lineTo(ex, ey);
  ctx.stroke();
  const ang = Math.atan2(ey - sy, ex - sx);
  const h = 6;
  ctx.beginPath();
  ctx.moveTo(ex, ey);
  ctx.lineTo(ex - h * Math.cos(ang - 0.4), ey - h * Math.sin(ang - 0.4));
  ctx.lineTo(ex - h * Math.cos(ang + 0.4), ey - h * Math.sin(ang + 0.4));
  ctx.closePath();
  ctx.fill();
}

function legend(
  ctx: CanvasRenderingContext2D,
  s: Record<string, string>,
  entries: Array<{ color: string; text: string }>,
) {
  ctx.font = '12px ui-monospace, Menlo, Consolas, monospace';
  let y = 16;
  for (const e of entries) {
    ctx.fillStyle = e.color;
    ctx.fillRect(10, y - 8, 10, 3);
    ctx.fillStyle = s.text;
    ctx.fillText(e.text, 26, y);
    y += 16;
  }
}

/**
 * Act 1: both bases projected onto two coordinates, at one shared scale.
 *
 * The warm starburst is tight and near-orthogonal; the neutral one sprawls. That
 * difference IS the orthogonality defect the panel reports numerically, and
 * drawing them at different scales would erase it.
 */
export function drawBases(
  canvas: HTMLCanvasElement,
  R: Mat,
  B: Mat,
  proj: Projection,
): void {
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const s = styles();
  clear(ctx, canvas, s);

  const pts: Array<[number, number]> = [];
  for (const row of R) pts.push([row[proj.i], row[proj.j]]);
  for (const row of B) pts.push([row[proj.i], row[proj.j]]);
  const v = fitViewport(canvas, pts);
  drawAxes(ctx, canvas, v, s);

  // Public basis first, so the short private vectors are never hidden under it.
  for (const row of B) arrow(ctx, v, row[proj.i], row[proj.j], s.pub, 1.2);
  for (const row of R) arrow(ctx, v, row[proj.i], row[proj.j], s.priv, 2.2);

  legend(ctx, s, [
    { color: s.priv, text: 'private basis R (short, near-orthogonal)' },
    { color: s.pub, text: 'public basis B (long, skewed)' },
  ]);
  ctx.fillStyle = s.text;
  ctx.font = '11px ui-monospace, Menlo, Consolas, monospace';
  ctx.fillText(
    `projected onto coordinates ${proj.i} and ${proj.j}; both bases at one scale`,
    10,
    canvas.height - 10,
  );
}

/**
 * The exact projection of the fundamental parallelepiped
 * P(R) = { x*R : x in [-1/2, 1/2)^n }.
 *
 * Projecting a parallelepiped gives a ZONOGON -- the Minkowski sum of the
 * projected basis rows as segments -- not a parallelogram. Computed by sorting
 * the generators by angle and walking them, which traces the convex hull
 * exactly. This is why the shape has many corners rather than four, and those
 * corners are exactly what leaks the basis.
 */
export function zonogon(rows: Array<[number, number]>): Array<[number, number]> {
  const gens = rows
    .map(([x, y]) => {
      // The zonotope is symmetric, so fold every generator into the upper half
      // plane before sorting by angle.
      const ang = Math.atan2(y, x);
      return ang < 0 || (ang === 0 && x < 0) ? ([-x, -y] as [number, number]) : ([x, y] as [number, number]);
    })
    .filter(([x, y]) => Math.abs(x) > 1e-12 || Math.abs(y) > 1e-12);
  gens.sort((a, b) => Math.atan2(a[1], a[0]) - Math.atan2(b[1], b[0]));
  let px = 0;
  let py = 0;
  for (const [x, y] of gens) {
    px -= x / 2;
    py -= y / 2;
  }
  const out: Array<[number, number]> = [[px, py]];
  for (const [x, y] of gens) {
    px += x;
    py += y;
    out.push([px, py]);
  }
  for (const [x, y] of gens) {
    px -= x;
    py -= y;
    out.push([px, py]);
  }
  return out;
}

/**
 * Act 4: the signature cloud.
 *
 * Each dot is one signature offset s - h. Under round-off signing these fill
 * P(R) uniformly, right into the corners; under Gaussian (Klein) signing they
 * form a round blob that has no corners to learn.
 */
export function drawSignatureCloud(
  canvas: HTMLCanvasElement,
  offsets: Vec[],
  R: Mat | null,
  proj: Projection,
  opts: { showParallelepiped: boolean; recovered?: Mat | null } = { showParallelepiped: true },
): void {
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const s = styles();
  clear(ctx, canvas, s);

  const pts: Array<[number, number]> = offsets.map((o) => [o[proj.i], o[proj.j]]);
  let hull: Array<[number, number]> = [];
  if (R && opts.showParallelepiped) {
    hull = zonogon(R.map((row) => [row[proj.i], row[proj.j]] as [number, number]));
  }
  const v = fitViewport(canvas, pts.concat(hull));
  drawAxes(ctx, canvas, v, s);

  ctx.fillStyle = s.pub;
  ctx.globalAlpha = 0.55;
  for (const [x, y] of pts) {
    const [sx, sy] = toScreen(v, x, y);
    ctx.fillRect(sx - 1, sy - 1, 2, 2);
  }
  ctx.globalAlpha = 1;

  if (hull.length > 2) {
    ctx.strokeStyle = s.priv;
    ctx.lineWidth = 1.8;
    ctx.beginPath();
    const [x0, y0] = toScreen(v, hull[0][0], hull[0][1]);
    ctx.moveTo(x0, y0);
    for (let i = 1; i < hull.length; i++) {
      const [sx, sy] = toScreen(v, hull[i][0], hull[i][1]);
      ctx.lineTo(sx, sy);
    }
    ctx.closePath();
    ctx.stroke();
  }

  if (opts.recovered) {
    ctx.strokeStyle = s.bad;
    ctx.setLineDash([4, 3]);
    ctx.lineWidth = 1.6;
    for (const row of opts.recovered) {
      const [sx, sy] = toScreen(v, 0, 0);
      const [ex, ey] = toScreen(v, row[proj.i] / 2, row[proj.j] / 2);
      ctx.beginPath();
      ctx.moveTo(sx, sy);
      ctx.lineTo(ex, ey);
      ctx.stroke();
    }
    ctx.setLineDash([]);
  }

  const items = [{ color: s.pub, text: `${offsets.length} signature offsets s - h` }];
  if (hull.length > 2) items.push({ color: s.priv, text: 'true P(R), projected exactly' });
  if (opts.recovered) items.push({ color: s.bad, text: 'recovered basis directions' });
  legend(ctx, s, items);
}

/** Draw nothing but a message -- used before an exhibit has been run. */
export function drawPlaceholder(canvas: HTMLCanvasElement, message: string): void {
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  const s = styles();
  clear(ctx, canvas, s);
  ctx.fillStyle = s.text;
  ctx.font = '13px ui-monospace, Menlo, Consolas, monospace';
  ctx.textAlign = 'center';
  ctx.fillText(message, canvas.width / 2, canvas.height / 2);
  ctx.textAlign = 'start';
}
